services:
  localstack:
    image: localstack/localstack:latest
    container_name: it-localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3,sqs,ses,dynamodb
      - DEBUG=1
      - AWS_DEFAULT_REGION=us-west-1
      - LOCALSTACK_AUTH_TOKEN=${LOCALSTACK_AUTH_TOKEN:-""}
    volumes:
      - ./init-aws.sh:/etc/localstack/init/ready.d/init-aws.sh
      - ./localstack-data:/var/lib/localstack
      - /var/run/docker.sock:/var/run/docker.sock
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -sf http://localhost:4566/_localstack/health >/dev/null && test -f /var/lib/localstack/init-complete"
        ]
      interval: 5s
      timeout: 5s
      retries: 30
      start_period: 10s

  fastapi:
    ports:
      - "8000:8000"
    build: ./backend 
    container_name: it-fastapi
    depends_on:
      localstack:
        condition: service_healthy
    env_file:
      - .env
    environment:
      - SQS_QUEUE_URL=${SQS_QUEUE_URL}
      - S3_BUCKET_NAME=${S3_BUCKET_NAME}
      - AWS_REGION=${AWS_REGION}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - LOCALSTACK_AUTH_TOKEN=${LOCALSTACK_AUTH_TOKEN}
    volumes:
      - ./backend:/app 

  celery:
    build: ./backend 
    container_name: it-celery
    entrypoint: sh -c "PYTHONPATH=/app celery -A app.tasks.image_tasks worker --loglevel=info -P gevent"
    depends_on:
      localstack:
        condition: service_healthy
    env_file: .env
    volumes:
      - ./backend:/app 
volumes:
  db_data: