version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: prod-postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=fastapi
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d fastapi"]
      interval: 5s
      timeout: 5s
      retries: 5

  fastapi:
    image: ${DOCKERHUB_USERNAME}/${DOCKER_REPO}:latest # Pulls from Docker Hub instead of building local code
    container_name: prod-fastapi
    ports:
      - "80:8000" # Open on port 80 for normal web traffic
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@postgres:5432/fastapi
      - SQS_QUEUE_URL=${SQS_QUEUE_URL}      # Real AWS SQS URL injected by GitHub
      - S3_BUCKET_NAME=${S3_BUCKET_NAME}    # Real AWS S3 bucket name
      - AWS_REGION=us-east-1
      - ADMIN_EMAIL=madnands5@gmail.com
      # NOTICE: LOCALSTACK_ENDPOINT is gone! Boto3 will now automatically talk to real AWS.

  celery:
    image: ${DOCKERHUB_USERNAME}/${DOCKER_REPO}:latest # Uses the exact same Docker Hub image
    container_name: prod-celery
    entrypoint: sh -c "PYTHONPATH=/app celery -A app.tasks.image_tasks worker --loglevel=info -P gevent"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@postgres:5432/fastapi
      - SQS_QUEUE_URL=${SQS_QUEUE_URL}
      - S3_BUCKET_NAME=${S3_BUCKET_NAME}
      - AWS_REGION=us-east-1

volumes:
  db_data: