services:
  localstack:
    image: localstack/localstack:latest
    container_name: it-localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3,sqs,ses
      - DEBUG=1
      - LOCALSTACK_AUTH_TOKEN=${LOCALSTACK_AUTH_TOKEN:-""}
    volumes:
      - ./init-aws.sh:/etc/localstack/init/ready.d/init-aws.sh
      - ./localstack-data:/var/lib/localstack
      - /var/run/docker.sock:/var/run/docker.sock
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:4566/_localstack/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  postgres:
    image: postgres:16-alpine
    container_name: it-postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=fastapi
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d fastapi"]
      interval: 5s
      timeout: 5s
      retries: 5

  fastapi:
    ports:
      - "8000:8000"
    build: .
    container_name: it-fastapi
    depends_on:
      localstack:
        condition: service_healthy
      postgres:
        condition: service_healthy
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - SQS_QUEUE_URL=${SQS_QUEUE_URL}
      - S3_BUCKET_NAME=${S3_BUCKET_NAME}
      - AWS_REGION=${AWS_REGION}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - LOCALSTACK_AUTH_TOKEN=${LOCALSTACK_AUTH_TOKEN}
    volumes:
      - .:/app
  celery:
    build: .
    container_name: it-celery
    # This overrides the entrypoint to run ONLY the worker
    entrypoint: celery -A app.tasks.image_tasks worker --loglevel=info -P gevent
    depends_on:
      localstack:
        condition: service_healthy
      postgres:
        condition: service_healthy
    env_file: .env
    volumes:
      - .:/app
volumes:
  db_data: # This fixes the 'undefined volume' error