apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery
spec:
  replicas: 1
  selector:
    matchLabels:
      app: celery
  template:
    metadata:
      labels:
        app: celery
    spec:
      containers:
        - name: celery
          image: it-fastapi:local
          command: ["sh", "-c"]
          args:
            - PYTHONPATH=/app celery -A app.tasks.image_tasks worker --loglevel=info -P gevent
          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: app-secrets