apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  SQS_QUEUE_URL: "sqs://localstack:4566/000000000000/image-processing-queue"
  S3_BUCKET_NAME: "my-test-bucket"
  AWS_REGION: "us-west-1"
  LOCALSTACK_ENDPOINT: "http://localstack:4566"
  CELERY_TASK_QUEUE_URL: "sqs://localstack:4566/000000000000/simple-celery-queue"
  DYNAMO_IMAGES_TABLE: "images"
  CONTAINER_ROLE: "web"
  CELERY_QUEUE_NAME: "simple-celery-queue"
  USER_POOL_ID: 'us-west-1_jJScGzggp'
  USER_POOL_CLIENT_ID: '6fgh9mc6cuvllacasrafmas563'
  ADMIN_EMAIL: "madnands5@gmail.com"
