apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: test
  AWS_SECRET_ACCESS_KEY: test
  LOCALSTACK_AUTH_TOKEN: ls-VEsOwoXA-CiCu-5549-CIWa-SAkIfiSI6952