"""add image s3_processed_file field

Revision ID: 746be983408a
Revises: 5d0a8e4740eb
Create Date: 2026-06-19 16:21:31.789213

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '746be983408a'
down_revision: Union[str, Sequence[str], None] = '5d0a8e4740eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('s3_processed_file', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('images', 's3_processed_file')
    # ### end Alembic commands ###
