name: CI/CD Pipeline

on:
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      action:
        description: 'Action'
        required: true
        type: choice
        options: [deploy, destroy]

jobs:
  build:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - uses: actions/checkout@v4
      
      - name: Build & Push
        run: |
          # 1. Build the image combining your username and repo secrets
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKER_REPO }}:latest ./backend
          
          # 2. Log in using your GitHub Secrets
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
          
          # 3. Push the image up to Docker Hub
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKER_REPO }}:latest

  infra:
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    env: 
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - uses: actions/checkout@v4

      # Installs Terraform CLI on the GitHub runner
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.7.0" # You can adjust this to match your local Terraform version

      - name: Execute
        run: |
          terraform init
          if [ "${{ github.event.inputs.action }}" == "deploy" ]; then
            terraform apply -auto-approve
          else
            terraform destroy -auto-approve
          fi